#ifndef QUEUE_MAP
#define QUEUE_MAP

#define GUOJIN_BROKER_ID_QUEUE_MAP 12
#define GUOJIN_SAFE_THREASHOLD_QUEUE_MAP 17
#define GUOJIN_ORDER_STATE_QUEUE_MAP 5
#define GUOJIN_TRADE_PRICE_QUEUE_MAP 8
#define GUOJIN_TRADE_QUANTITY_QUEUE_MAP 9

#define ZHONGXIN_BROKER_ID_QUEUE_MAP 1
#define ZHONGXIN_SAFE_THREASHOLD_QUEUE_MAP 22
#define ZHONGXIN_ORDER_STATE_QUEUE_MAP 7
#define ZHONGXIN_TRADE_PRICE_QUEUE_MAP 10
#define ZHONGXIN_TRADE_QUANTITY_QUEUE_MAP 11

#define GTJA_BROKER_ID_QUEUE_MAP 9
#define GTJA_SAFE_THREASHOLD_QUEUE_MAP 16
#define GTJA_ORDER_STATE_QUEUE_MAP 12
#define GTJA_TRADE_PRICE_QUEUE_MAP 7
#define GTJA_TRADE_QUANTITY_QUEUE_MAP 10

#define TEST_BROKER_ID_QUEUE_MAP 2
#define TEST_SAFE_THREASHOLD_QUEUE_MAP 15
#define TEST_ORDER_STATE_QUEUE_MAP 5
#define TEST_TRADE_PRICE_QUEUE_MAP 8
#define TEST_TRADE_QUANTITY_QUEUE_MAP 9



#endif